"""initial_task_execution

Revision ID: cf1c62d50694
Revises: 
Create Date: 2026-03-09 22:28:27.598546

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf1c62d50694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_execution',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'RUNNING', 'RETRYING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PARTIAL', name='taskstatus', create_constraint=True), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('status_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('parent_task_id', sa.UUID(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['task_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_execution_created_at'), 'task_execution', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_execution_parent_task_id'), 'task_execution', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_task_execution_task_name'), 'task_execution', ['task_name'], unique=False)
    op.create_index(op.f('ix_task_execution_tenant_id'), 'task_execution', ['tenant_id'], unique=False)
    op.create_index('ix_task_execution_tenant_status', 'task_execution', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_execution_tenant_status', table_name='task_execution')
    op.drop_index(op.f('ix_task_execution_tenant_id'), table_name='task_execution')
    op.drop_index(op.f('ix_task_execution_task_name'), table_name='task_execution')
    op.drop_index(op.f('ix_task_execution_parent_task_id'), table_name='task_execution')
    op.drop_index(op.f('ix_task_execution_created_at'), table_name='task_execution')
    op.drop_table('task_execution')
    # ### end Alembic commands ###
